// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace squaredup.SquaredUpPackage.Squaredup
{
    public static class GetDataStreams
    {
        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Squaredup = Pulumi.Squaredup;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Squaredup.GetDataStreams.Invoke(new()
        ///     {
        ///         DataSourceId = "datasource-id",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetDataStreamsResult> InvokeAsync(GetDataStreamsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDataStreamsResult>("squaredup:index/getDataStreams:getDataStreams", args ?? new GetDataStreamsArgs(), options.WithDefaults());

        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Squaredup = Pulumi.Squaredup;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Squaredup.GetDataStreams.Invoke(new()
        ///     {
        ///         DataSourceId = "datasource-id",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetDataStreamsResult> Invoke(GetDataStreamsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDataStreamsResult>("squaredup:index/getDataStreams:getDataStreams", args ?? new GetDataStreamsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDataStreamsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the data source to get data streams for
        /// </summary>
        [Input("dataSourceId", required: true)]
        public string DataSourceId { get; set; } = null!;

        /// <summary>
        /// Name of the data stream definition to get particular data stream details
        /// </summary>
        [Input("dataStreamDefinitionName")]
        public string? DataStreamDefinitionName { get; set; }

        public GetDataStreamsArgs()
        {
        }
        public static new GetDataStreamsArgs Empty => new GetDataStreamsArgs();
    }

    public sealed class GetDataStreamsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the data source to get data streams for
        /// </summary>
        [Input("dataSourceId", required: true)]
        public Input<string> DataSourceId { get; set; } = null!;

        /// <summary>
        /// Name of the data stream definition to get particular data stream details
        /// </summary>
        [Input("dataStreamDefinitionName")]
        public Input<string>? DataStreamDefinitionName { get; set; }

        public GetDataStreamsInvokeArgs()
        {
        }
        public static new GetDataStreamsInvokeArgs Empty => new GetDataStreamsInvokeArgs();
    }


    [OutputType]
    public sealed class GetDataStreamsResult
    {
        /// <summary>
        /// ID of the data source to get data streams for
        /// </summary>
        public readonly string DataSourceId;
        /// <summary>
        /// Name of the data stream definition to get particular data stream details
        /// </summary>
        public readonly string? DataStreamDefinitionName;
        /// <summary>
        /// Data Streams are used to query third party APIs and SquaredUp visualizes the results
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDataStreamsDataStreamResult> DataStreams;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetDataStreamsResult(
            string dataSourceId,

            string? dataStreamDefinitionName,

            ImmutableArray<Outputs.GetDataStreamsDataStreamResult> dataStreams,

            string id)
        {
            DataSourceId = dataSourceId;
            DataStreamDefinitionName = dataStreamDefinitionName;
            DataStreams = dataStreams;
            Id = id;
        }
    }
}
