// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace squaredup.SquaredUpPackage.Squaredup.Outputs
{

    [OutputType]
    public sealed class GetDatasourcesPluginResult
    {
        public readonly string Author;
        public readonly string Category;
        public readonly string Description;
        public readonly string DisplayName;
        public readonly string Id;
        public readonly string LastUpdated;
        public readonly bool OnPrem;
        public readonly string Version;

        [OutputConstructor]
        private GetDatasourcesPluginResult(
            string author,

            string category,

            string description,

            string displayName,

            string id,

            string lastUpdated,

            bool onPrem,

            string version)
        {
            Author = author;
            Category = category;
            Description = description;
            DisplayName = displayName;
            Id = id;
            LastUpdated = lastUpdated;
            OnPrem = onPrem;
            Version = version;
        }
    }
}
