// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace squaredup.SquaredUpPackage.Squaredup.Outputs
{

    [OutputType]
    public sealed class GetDataStreamsDataStreamResult
    {
        public readonly string DataSourceName;
        public readonly string DefinitionName;
        public readonly string DisplayName;
        public readonly string Id;
        public readonly string LastUpdated;
        public readonly string ParentPluginId;
        public readonly string ParentPluginVersion;
        public readonly string Type;

        [OutputConstructor]
        private GetDataStreamsDataStreamResult(
            string dataSourceName,

            string definitionName,

            string displayName,

            string id,

            string lastUpdated,

            string parentPluginId,

            string parentPluginVersion,

            string type)
        {
            DataSourceName = dataSourceName;
            DefinitionName = definitionName;
            DisplayName = displayName;
            Id = id;
            LastUpdated = lastUpdated;
            ParentPluginId = parentPluginId;
            ParentPluginVersion = parentPluginVersion;
            Type = type;
        }
    }
}
