# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetDataStreamsDataStreamResult',
    'GetDatasourcesPluginResult',
]

@pulumi.output_type
class GetDataStreamsDataStreamResult(dict):
    def __init__(__self__, *,
                 data_source_name: str,
                 definition_name: str,
                 display_name: str,
                 id: str,
                 last_updated: str,
                 parent_plugin_id: str,
                 parent_plugin_version: str,
                 type: str):
        pulumi.set(__self__, "data_source_name", data_source_name)
        pulumi.set(__self__, "definition_name", definition_name)
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "last_updated", last_updated)
        pulumi.set(__self__, "parent_plugin_id", parent_plugin_id)
        pulumi.set(__self__, "parent_plugin_version", parent_plugin_version)
        pulumi.set(__self__, "type", type)

    @property
    @pulumi.getter(name="dataSourceName")
    def data_source_name(self) -> str:
        return pulumi.get(self, "data_source_name")

    @property
    @pulumi.getter(name="definitionName")
    def definition_name(self) -> str:
        return pulumi.get(self, "definition_name")

    @property
    @pulumi.getter(name="displayName")
    def display_name(self) -> str:
        return pulumi.get(self, "display_name")

    @property
    @pulumi.getter
    def id(self) -> str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> str:
        return pulumi.get(self, "last_updated")

    @property
    @pulumi.getter(name="parentPluginId")
    def parent_plugin_id(self) -> str:
        return pulumi.get(self, "parent_plugin_id")

    @property
    @pulumi.getter(name="parentPluginVersion")
    def parent_plugin_version(self) -> str:
        return pulumi.get(self, "parent_plugin_version")

    @property
    @pulumi.getter
    def type(self) -> str:
        return pulumi.get(self, "type")


@pulumi.output_type
class GetDatasourcesPluginResult(dict):
    def __init__(__self__, *,
                 author: str,
                 category: str,
                 description: str,
                 display_name: str,
                 id: str,
                 last_updated: str,
                 on_prem: bool,
                 version: str):
        pulumi.set(__self__, "author", author)
        pulumi.set(__self__, "category", category)
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "last_updated", last_updated)
        pulumi.set(__self__, "on_prem", on_prem)
        pulumi.set(__self__, "version", version)

    @property
    @pulumi.getter
    def author(self) -> str:
        return pulumi.get(self, "author")

    @property
    @pulumi.getter
    def category(self) -> str:
        return pulumi.get(self, "category")

    @property
    @pulumi.getter
    def description(self) -> str:
        return pulumi.get(self, "description")

    @property
    @pulumi.getter(name="displayName")
    def display_name(self) -> str:
        return pulumi.get(self, "display_name")

    @property
    @pulumi.getter
    def id(self) -> str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> str:
        return pulumi.get(self, "last_updated")

    @property
    @pulumi.getter(name="onPrem")
    def on_prem(self) -> bool:
        return pulumi.get(self, "on_prem")

    @property
    @pulumi.getter
    def version(self) -> str:
        return pulumi.get(self, "version")


