// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetDataStreamsDataStream {
    dataSourceName: string;
    definitionName: string;
    displayName: string;
    id: string;
    lastUpdated: string;
    parentPluginId: string;
    parentPluginVersion: string;
    type: string;
}

export interface GetDatasourcesPlugin {
    author: string;
    category: string;
    description: string;
    displayName: string;
    id: string;
    lastUpdated: string;
    onPrem: boolean;
    version: string;
}

